source "https://rubygems.org"

gem "lita"
gem "lita-slack"
gem "dotenv"

gem "lita-applause"
gem "lita-boardgamegeek"
gem "lita-catfacts"
gem "lita-chm"
gem "lita-dice"
gem "lita-directions"
gem "lita-dogebomb"
gem "lita-down-for-everyone"
gem "lita-eightball"
gem "lita-excuses"
gem "lita-fortune"
gem "lita-github-status"
gem "lita-goforit"
gem "lita-google"
gem "lita-google-images"
gem "lita-hal-9000"
gem "lita-howdoi"
gem "lita-nashdev-resources", '>= 1.0.1'
gem "lita-poll"
gem "lita-rimshot"
gem "lita-rules"
gem "lita-snack"
gem "lita-shipit"
gem "lita-time"
gem "lita-trivia", '1.0.0'
gem "lita-vader"
gem "lita-weather"
gem "lita-wikipedia"
gem "lita-xkcd"
