source "https://rubygems.org"

gem "lita"
gem "lita-slack"
gem "dotenv"

gem "lita-catfacts"
gem "lita-chm"
gem "lita-dice"
gem "lita-dogebomb"
gem "lita-down-for-everyone"
gem "lita-eightball"
gem "lita-excuses"
gem "lita-fortune"
gem "lita-github-status"
gem "lita-goforit"
gem "lita-google"
gem "lita-google-images"
gem "lita-hal-9000"
gem "lita-howdoi"
gem "lita-rimshot"
gem "lita-rules"
gem "lita-shipit"
gem "lita-vader"
gem "lita-wikipedia"
gem "lita-xkcd"
